"""
JoinQuant entry script for the Dynamic Mean Reversion & Multi-Factor Flow Alpha strategy.

The script keeps the platform-facing hooks at the top level and delegates the
benchmark regime detection, candidate ranking, portfolio capacity management,
and technical exit checks to the modular strategy package.
"""

import jqdata

from modular_dmr_mfa import DynamicMeanReversionFlowAlphaStrategy


STRATEGY = DynamicMeanReversionFlowAlphaStrategy()


def initialize(context):
    """Initializes the strategy and registers the trading-day callbacks."""

    log.info(
        "=== Initialize: Dynamic Mean Reversion + Money Flow Filter + Technical Exit ==="
    )
    g.strategy = STRATEGY
    g.strategy.initialize(context)

    run_daily(before_market_open, time="before_open")
    run_daily(market_open, time="open")
    run_daily(check_stop_loss_take_profit, time="11:25")
    run_daily(check_stop_loss_take_profit, time="14:50")


def before_market_open(context):
    """Runs the pre-open state maintenance hook."""

    g.strategy.before_market_open(context)


def market_open(context):
    """Runs the market-open capacity adjustment and cash deployment hook."""

    orders = g.strategy.market_open(context)
    _execute_target_value_orders(orders)


def check_stop_loss_take_profit(context):
    """Runs the intraday technical and hard-threshold exit checks."""

    orders = g.strategy.check_stop_loss_take_profit(context)
    _execute_target_value_orders(orders)


def after_market_close(context):
    """Retains the explicit post-close hook used by the strategy interface."""

    g.strategy.after_market_close(context)


def _execute_target_value_orders(orders):
    """Submits normalized target-value orders generated by the modular package."""

    for order in orders:
        order_target_value(order.security, order.target_value)
