"""
Shared runtime objects for the Dynamic Mean Reversion & Multi-Factor Flow Alpha strategy.

The strategy requires only a compact mutable state object and a normalized
target-value order type because every rebalance and exit instruction is
expressed through target portfolio value updates.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class StrategyRuntimeState:
    """Mutable state carried across the daily lifecycle of the strategy."""

    trading_day_counter: int = 0
    active_stock_num: int = 5
    portfolio_high: float | None = None


@dataclass(frozen=True)
class TargetValueOrder:
    """Normalized target-value instruction generated by portfolio modules."""

    security: str
    target_value: float
    reason: str = ""
